name: braze_plugin_web_example
description: Demonstrates how to use the braze_plugin_web plugin. Based on the official braze_plugin example.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  braze_plugin_web:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
